export const types = Object.freeze({
    FORECAST_IS_FILTERED: 'FORECAST_IS_FILTERED',
    FORECAST_START_FETCHING: 'FORECAST_START_FETCHING',
    FORECAST_STOP_FETCHING: 'FORECAST_STOP_FETCHING',
    FORECAST_FILL: 'FORECAST_FILL',
    FORECAST_SET_FETCHING_ERROR: 'FORECAST_SET_FETCHING_ERROR',
    FORECAST_NOT_DAYS: 'FORECAST_NOT_DAYS',
    FORECAST_FILTER_TYPE: 'FORECAST_FILTER_TYPE',
    FORECAST_FILTER_MIN: 'FORECAST_FILTER_MIN',
    FORECAST_FILTER_MAX: 'FORECAST_FILTER_MAX',

    // Async
    FORECAST_FETCH_ASYNC: 'FORECAST_FETCH_ASYNC',
})
